# Generated by Django 5.1.6 on 2025-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artwork_movement_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
